#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
from src.inout import optP
from src.calculate_order import calculate_order


options = optP()
calculate_order(
    options.struct_in, options.traj_in, options.sel1, options.sel2,
    options.dt, options.gridn, options.center, options.outfile, options.plot,
    options.mindat, options.leaflets, options.leafletatom, options.time
)
